### ISSUE TITLE
Terminix has been renamed to Tilix due to trademark issue

### ISSUE THREAD

**Issue by ivoarch** [arcticicestudio/nord-terminix#14]
More information at https://github.com/gnunn1/tilix/issues/815

**Comment by arcticicestudio** [comment]
Thanks for the notification 👍
I'm aware of this since [I've been part of the discussion](https://github.com/gnunn1/tilix/issues/815#issuecomment-284132700) for the new name and there's also already PR #13.
Haven't got the time to update the project and all assets yet. I think I'll also implement a migration function for the `install.sh` script.

**Comment by ivoarch** [comment]
Sorry I had not seen #13 .
Keep your great work with nord .

**Comment by arcticicestudio** [comment]
> Duplicate of #13

🚢 Shipped in release version 🏷 [0.3.0](https://github.com/arcticicestudio/nord-tilix/releases/tag/v0.3.0).
